test:
  variables:
    LANG: C.UTF-8
  script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip python3 python3-pip
  - pip3 install -r requirements.txt
  - python3 ruter-cli.py "Oslo S" "Lillehammer"
